/*
 * main.config.h
 *
 *  Created on: Jan 15, 2016
 *      Author: denis.bilyk
 */

#ifndef MAIN_CONFIG_H_
#define MAIN_CONFIG_H_

#include "pins.h"

RCC_Periphery GPIOA_RCC = RCC_PERIPHERY(APB2, GPIOA);
RCC_Periphery GPIOB_RCC = RCC_PERIPHERY(APB2, GPIOB);
RCC_Periphery GPIOC_RCC = RCC_PERIPHERY(APB2, GPIOC);
RCC_Periphery GPIOD_RCC = RCC_PERIPHERY(APB2, GPIOD);


GPIO_Pin LED_C13 = GPIO_PIN(GPIOC, 13);
GPIO_Pin LED_ESP_STATUS_OK = GPIO_PIN(GPIOB, 8);
GPIO_Pin LED_ESP_STATUS_ERR = GPIO_PIN(GPIOB, 9);

GPIO_Pin LED_ESP_INIT_OK = GPIO_PIN(GPIOA, 0);
GPIO_Pin LED_ESP_INIT_ERR = GPIO_PIN(GPIOA, 1);




GPIO_Pin NRF_SPI_SCK = GPIO_PIN(GPIOA, 5);
GPIO_Pin NRF_SPI_MISO = GPIO_PIN(GPIOA, 6);
GPIO_Pin NRF_SPI_MOSI =	GPIO_PIN(GPIOA, 7);
GPIO_Pin NRF_CE = GPIO_PIN(GPIOB, 0);
GPIO_Pin NRF_CSN = GPIO_PIN(GPIOA, 4);

GPIO_Pin NRF_CE_2 = GPIO_PIN(GPIOB, 1);
GPIO_Pin NRF_CSN_2 = GPIO_PIN(GPIOB, 10);

#define RX_ADDR_0 0x27272727E0
#define RX_ADDR_1 0xE7E7E7E7E1
#define RX_ADDR_2 0xE7E7E7E7E2
#define RX_ADDR_3 0xE7E7E7E7E3
#define RX_ADDR_4 0xE7E7E7E7E4
#define RX_ADDR_5 0xE7E7E7E7E5


#endif /* MAIN_CONFIG_H_ */
